@startuml
abstract class bases.BaseDialog {
# SharedPreferencesUtil sharedPreferencesUtil
+ Dialog onCreateDialog(Bundle)
# Dialog createDialogInstance(Bundle)
# boolean shouldSetTransparentBackground()
# {abstract}int getLayoutResId()
# {abstract}void setupViews(Dialog)
}


abstract class bases.BaseActivity {
- {static} String TAG
# SharedPreferencesUtil sharedPreferencesUtil
# IDatabaseService databaseService
# IAdapterService adapterService
# IDialogService dialogService
# DrawerLayout drawerLayout
- Runnable onPermissionGrantedCallback
# ActivityResultLauncher<String[]> requestPermissionLauncher
# void onCreate(Bundle)
# void setContent(int,int)
# void setupMenu()
+ void openDrawer()
+ void closeDrawer()
+ void onNavigate(int)
# void navigateToUserHome(User)
# ArrayAdapter<String> createStyledSearchAdapter(String[])
# ArrayAdapter<String> createStyledSearchAdapter(List<String>)
# void setGreeting(int,User)
+ void onNavigate(int,Bundle)
# void vibrateDevice()
# void runWithPermissions(Runnable,String)
# void runWithPermission(String,Runnable)
- void requestPermissions(String)
# void openAppSettings()
# void onPermissionsResult(Map<String,Boolean>)
}




androidx.fragment.app.DialogFragment <|-- bases.BaseDialog
ui.MenuNavigationListener <|.. bases.BaseActivity
androidx.appcompat.app.AppCompatActivity <|-- bases.BaseActivity
@enduml
