@startuml
class com.example.sagivproject.utils.ImageUtil {
- {static} String BASE64_PREFIX
+ String convertTo64Base(ImageView)
+ void loadImage(String,ImageView)
}


class com.example.sagivproject.utils.SharedPreferencesUtil {
- {static} String PREF_NAME
- {static} String KEY_USER
- {static} String KEY_DARK_MODE
- SharedPreferences sharedPreferences
- Gson gson
+ void saveString(String,String)
+ String getString(String,String)
+ void saveInt(String,int)
+ int getInt(String,int)
+ void saveBoolean(String,boolean)
+ boolean getBoolean(String,boolean)
+ void clear()
+ void remove(String)
+ boolean contains(String)
+ void saveObject(String,T)
+ T getObject(String,Class<T>)
+ void saveUser(User)
+ User getUser()
+ void signOutUser()
+ boolean isUserNotLoggedIn()
+ boolean isDarkMode()
+ void setDarkMode(boolean)
+ String getUserId()
}


class com.example.sagivproject.utils.CalendarUtil {
+ {static} String DEFAULT_DATE_FORMAT
+ void openDatePicker(Context,long,OnDateSelectedListener,boolean,boolean,String)
+ String formatDate(long)
+ String formatDate(long,String)
}


interface com.example.sagivproject.utils.CalendarUtil$OnDateSelectedListener {
~ void onDateSelected(long,String)
}

class com.example.sagivproject.utils.Validator {
- {static} int MIN_AGE
+ boolean isNameNotValid(String)
+ boolean isEmailNotValid(String)
+ boolean isPhoneNotValid(String)
+ boolean isPasswordNotValid(String)
+ boolean isAgeNotValid(long)
}




com.example.sagivproject.utils.CalendarUtil +.. com.example.sagivproject.utils.CalendarUtil$OnDateSelectedListener
@enduml