@startuml
abstract class bases.BaseAdapter {
# List<T> dataList
+ void setData(List<T>)
+ int getItemCount()
# T getItem(int)
+ List<T> getItemList()
}


class bases.BaseAdapter$DiffCallback {
- List<T> oldList
- List<T> newList
+ int getOldListSize()
+ int getNewListSize()
+ boolean areItemsTheSame(int,int)
+ boolean areContentsTheSame(int,int)
}


class bases.MainApplication {
~ SharedPreferencesUtil sharedPreferencesUtil
+ void onCreate()
}




bases.Adapter <|-- bases.BaseAdapter
bases.BaseAdapter +.. bases.BaseAdapter$DiffCallback
bases.Callback <|-- bases.BaseAdapter$DiffCallback
android.app.Application <|-- bases.MainApplication
@enduml