@startuml
class services.impl.FallDetectionServiceImpl {
- Context context
+ void startMonitoring()
+ void stopMonitoring()
}


class services.impl.ForumCategoriesServiceImpl {
- {static} String CATEGORIES_PATH
+ void getCategories(IDatabaseService.DatabaseCallback<List<ForumCategory>>)
+ void addCategory(String,IDatabaseService.DatabaseCallback<Void>)
+ void deleteCategory(String,IDatabaseService.DatabaseCallback<Void>)
+ void updateCategoryName(String,String,IDatabaseService.DatabaseCallback<Void>)
}


abstract class services.impl.BaseDatabaseService {
- {static} String TAG
# DatabaseReference databaseReference
- String path
- Class<T> clazz
# String generateId()
# void create(T,IDatabaseService.DatabaseCallback<Void>)
# void get(String,IDatabaseService.DatabaseCallback<T>)
# void getAll(IDatabaseService.DatabaseCallback<List<T>>)
# void delete(String,IDatabaseService.DatabaseCallback<Void>)
# void update(String,UnaryOperator<T>,IDatabaseService.DatabaseCallback<T>)
# DatabaseReference readData(String)
# void writeData(String,Object,IDatabaseService.DatabaseCallback<Void>)
# void deleteData(String,IDatabaseService.DatabaseCallback<Void>)
# void getData(String,IDatabaseService.DatabaseCallback<T>)
# void getDataList(String,IDatabaseService.DatabaseCallback<List<T>>)
# void runTransaction(String,UnaryOperator<T>,IDatabaseService.DatabaseCallback<T>)
}




services.IFallDetectionService <|.. services.impl.FallDetectionServiceImpl
services.IForumCategoriesService <|.. services.impl.ForumCategoriesServiceImpl
services.impl.BaseDatabaseService <|-- services.impl.ForumCategoriesServiceImpl
@enduml