@startuml
class services.impl.MedicationServiceImpl {
- {static} String USERS_PATH
- {static} String MEDICATIONS_PATH
- {static} String FIELD_DAILY_STATS
+ String generateMedicationId()
+ String generateUsageId()
+ void createNewMedication(String,Medication,DatabaseCallback<Void>)
+ void getUserMedicationList(String,DatabaseCallback<List<Medication>>)
+ void deleteMedication(String,String,DatabaseCallback<Void>)
+ void updateMedication(String,Medication,DatabaseCallback<Void>)
+ void getMedicationUsageLogs(String,DatabaseCallback<List<MedicationUsage>>)
+ void clearMedicationUsageLogs(String,DatabaseCallback<Void>)
+ void clearMedicationUsageLogsForDate(String,String,DatabaseCallback<Void>)
+ void deleteMedicationUsageLog(String,String,String,DatabaseCallback<Void>)
- String getMedicationPath(String)
- String getMedicationItemPath(String,String)
}


class services.impl.ForumServiceImpl {
- {static} String FORUM_PATH
- IUserService userService
- CalendarUtil calendarUtil
- Map<String,User> userCache
- Map<String,ValueEventListener> listeners
+ void sendMessage(User,String,String,DatabaseCallback<Void>)
+ void listenToMessages(String,DatabaseCallback<List<ForumMessage>>)
+ void stopListeningToMessages(String)
+ void loadOlderMessages(String,String,int,DatabaseCallback<List<ForumMessage>>)
- void processMessages(List<ForumMessage>,DatabaseCallback<List<ForumMessage>>)
+ Map<String,User> getUserCache()
+ void clearUserCache()
+ void deleteMessage(String,String,DatabaseCallback<Void>)
- String getCategoryPath(String)
}




services.IMedicationService <|.. services.impl.MedicationServiceImpl
services.impl.BaseDatabaseService <|-- services.impl.MedicationServiceImpl
services.IForumService <|.. services.impl.ForumServiceImpl
services.impl.BaseDatabaseService <|-- services.impl.ForumServiceImpl
@enduml