@startuml
class services.impl.DatabaseService {
- IAuthService authService
- IUserService userService
- IMedicationService medicationService
- IMemoryGameService gameService
- IStatsService statsService
- IForumService forumService
- IImageService imageService
- IForumCategoriesService forumCategoriesService
- ITipOfTheDayService tipOfTheDayService
- IEmergencyService emergencyService
+ IAuthService getAuthService()
+ IUserService getUserService()
+ IMedicationService getMedicationService()
+ IMemoryGameService getGameService()
+ IStatsService getStatsService()
+ IForumService getForumService()
+ IImageService getImageService()
+ IForumCategoriesService getForumCategoriesService()
+ ITipOfTheDayService getTipOfTheDayService()
+ IEmergencyService getEmergencyService()
}


class services.impl.AdapterService {
- ForumAdapter forumAdapter
- ForumCategoryAdapter forumCategoryAdapter
- MedicationListAdapter medicationListAdapter
- MemoryGameAdapter memoryGameAdapter
- MemoryGameLogAdapter memoryGameLogAdapter
- UsersTableAdapter usersTableAdapter
- MedicationImagesTableAdapter medicationImagesTableAdapter
- LeaderboardAdapter leaderboardAdapter
- MedicationUsageAdapter medicationUsageAdapter
- EmergencyContactsAdapter emergencyContactsAdapter
- GraphAdapter graphAdapter
+ ForumAdapter getForumAdapter()
+ ForumCategoryAdapter getForumCategoryAdapter()
+ MedicationListAdapter getMedicationListAdapter()
+ MemoryGameAdapter getMemoryGameAdapter()
+ MemoryGameLogAdapter getMemoryGameLogAdapter()
+ UsersTableAdapter getUsersTableAdapter()
+ MedicationImagesTableAdapter getMedicationImagesTableAdapter()
+ LeaderboardAdapter getLeaderboardAdapter()
+ MedicationUsageAdapter getMedicationUsageAdapter()
+ EmergencyContactsAdapter getEmergencyContactsAdapter()
+ GraphAdapter getGraphAdapter()
}


class services.impl.AuthServiceImpl {
- {static} String ERROR_INVALID_CREDENTIALS
- {static} String ERROR_LOGIN
- {static} String ERROR_EMAIL_TAKEN
- {static} String ERROR_CHECKING_EMAIL
- {static} String ERROR_UPDATING_DETAILS
- IUserService userService
- SharedPreferencesUtil sharedPreferencesUtil
+ void login(String,String,LoginCallback)
+ void register(String,String,String,String,String,RegisterCallback)
+ void addUser(String,String,String,String,String,AddUserCallback)
+ void updateUser(User,String,String,String,String,String,UpdateUserCallback)
+ String logout()
- void createUser(String,String,String,String,String,DatabaseCallback<User>)
- void applyUserUpdate(User,String,String,String,String,String,UpdateUserCallback)
- void handleUserCreation(String,String,String,String,String,DatabaseCallback<User>,Consumer<String>)
}




services.IDatabaseService <|.. services.impl.DatabaseService
services.IAdapterService <|.. services.impl.AdapterService
services.IAuthService <|.. services.impl.AuthServiceImpl
@enduml