@startuml
class screens.LandingActivity {
# void onCreate(Bundle)
}

class screens.MathProblemsActivity {
- StringBuilder userInput
- Handler handler
- TextView tvCorrect
- User user
- TextView tvQuestion
- MaterialCardView cvAnswerContainer
- int correctAnswer
# void onCreate(Bundle)
- void fetchLatestStats()
- void updateStatsUI()
- void generateProblem()
- int rand(int,int)
- void setupKeypad()
- void deleteLast()
- void clearInput()
- void checkAnswer()
- DailyStats getTodayStats(String)
- void showFeedback(boolean)
}


class screens.MainActivity {
# void onCreate(Bundle)
}

class screens.LoginActivity {
# Validator validator
- EditText editTextEmail
# void onCreate(Bundle)
- void tryLogin()
- boolean validateInput(String,String)
}




bases.BaseActivity <|-- screens.LandingActivity
bases.BaseActivity <|-- screens.MathProblemsActivity
bases.BaseActivity <|-- screens.MainActivity
bases.BaseActivity <|-- screens.LoginActivity
@enduml
