@startuml
interface services.IUserService {
~ String generateUserId()
~ void createNewUser(User,DatabaseCallback<Void>)
~ void getUser(String,DatabaseCallback<User>)
~ void getUserList(DatabaseCallback<List<User>>)
~ void deleteUser(String,DatabaseCallback<Void>)
~ void getUserByEmailAndPassword(String,String,DatabaseCallback<User>)
~ void checkIfEmailExists(String,DatabaseCallback<Boolean>)
~ void updateUser(User,DatabaseCallback<Void>)
~ void updateUserRole(String,User.UserRole,DatabaseCallback<Void>)
}

interface services.ITipOfTheDayService {
~ void getTipForToday(IDatabaseService.DatabaseCallback<TipOfTheDay>)
~ void getAllTips(IDatabaseService.DatabaseCallback<List<TipOfTheDay>>)
~ void getTipByDate(String,IDatabaseService.DatabaseCallback<TipOfTheDay>)
~ void saveTipIfNotExists(TipOfTheDay,IDatabaseService.DatabaseCallback<TipOfTheDay>)
~ void saveTip(TipOfTheDay,IDatabaseService.DatabaseCallback<Void>)
~ void deleteTip(String,IDatabaseService.DatabaseCallback<Void>)
}

@enduml