@startuml
interface services.IForumService {
~ void sendMessage(User,String,String,DatabaseCallback<Void>)
~ void listenToMessages(String,DatabaseCallback<List<ForumMessage>>)
~ void loadOlderMessages(String,String,int,DatabaseCallback<List<ForumMessage>>)
~ void deleteMessage(String,String,DatabaseCallback<Void>)
~ void stopListeningToMessages(String)
~ Map<String,User> getUserCache()
~ void clearUserCache()
}

interface services.IForumCategoriesService {
~ void getCategories(DatabaseCallback<List<ForumCategory>>)
~ void addCategory(String,DatabaseCallback<Void>)
~ void deleteCategory(String,DatabaseCallback<Void>)
~ void updateCategoryName(String,String,DatabaseCallback<Void>)
}

interface services.IImageService {
~ void getAllImages(DatabaseCallback<List<ImageData>>)
~ void createImage(ImageData,DatabaseCallback<Void>)
~ void updateAllImages(List<ImageData>,DatabaseCallback<Void>)
~ void deleteImage(String,DatabaseCallback<Void>)
}

@enduml