@startuml
interface services.IFallDetectionService {
~ void startMonitoring()
~ void stopMonitoring()
}

interface services.IDialogService {
~ void showMedicationDialog(FragmentManager,Medication,MedicationDialog.OnMedicationSubmitListener)
~ void showUserDialog(FragmentManager,User,UserDialog.UserDialogListener)
~ void showEditForumCategoryDialog(FragmentManager,ForumCategory,EditForumCategoryDialog.EditForumCategoryDialogListener)
~ void showFullImageDialog(FragmentManager,Drawable)
~ void showProfileImageDialog(FragmentManager,boolean,ProfileImageDialog.ImagePickerListener)
~ void showEmergencyContactDialog(FragmentManager,EmergencyContact,EmergencyContactDialog.AddEmergencyContactListener)
~ void showConfirmDialog(FragmentManager,String,String,String,String,Runnable)
}

interface services.IEmergencyService {
~ String generateContactId()
~ void addContact(String,String,String,String,DatabaseCallback<Void>)
~ void deleteContact(String,String,DatabaseCallback<Void>)
~ void updateContact(String,EmergencyContact,DatabaseCallback<Void>)
~ void sendEmergencyAlert(Context,List<EmergencyContact>,String,DatabaseCallback<Void>)
}

@enduml