@startuml
class ui.SimpleXYGraphView {
- Paint axisPaint
- Paint gridPaint
- Paint pointPaint
- Paint textPaint
- Paint trendLinePaint
- Paint linePaint
- Paint barPaint
- Path linePath
- float paddingLeft
- float paddingBottom
- float paddingTop
- float pointSpacing
- Typeface headlineFont
- Typeface textFont
- List<Point> points
- List<String> xLabels
- String title
- String labelX
- String labelY
- GraphType graphType
- float scrollXOffset
- float lastTouchX
- void init(Context)
+ void setData(List<Point>,List<String>,String,String,String,GraphType)
+ boolean onTouchEvent(MotionEvent)
# void onDraw(Canvas)
+ boolean performClick()
- void drawGridY(Canvas,float,float,float,float)
- void drawYLabels(Canvas,float,float,float)
- void drawTrendLine(Canvas,float,float,float)
- void drawNoData(Canvas)
}


enum ui.GraphType {
+  LINE
+  BAR
}

class ui.SimpleXYGraphView$Point {
+ float x
+ float y
}

class ui.AppMenuFragment {
- {static} String ARG_MENU_TYPE
# SharedPreferencesUtil sharedPreferencesUtil
- OnNavigationListener navigationListener
- MenuType menuType
+ {static} AppMenuFragment newInstance(MenuType)
+ void onAttach(Context)
+ void onCreate(Bundle)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- void setupNavigationButton(View,int,int)
+ void onDetach()
+ MenuType getMenuType()
}


enum ui.MenuType {
+  ADMIN
+  LOGGED_IN
+  LOGGED_OUT
}

interface ui.AppMenuFragment$OnNavigationListener {
~ void onNavigate(int)
~ void onNavigate(int,Bundle)
}



android.view.View <|-- ui.SimpleXYGraphView
ui.SimpleXYGraphView +.. ui.SimpleXYGraphView$Point
androidx.fragment.app.Fragment <|-- ui.AppMenuFragment
ui.AppMenuFragment +.. ui.AppMenuFragment$OnNavigationListener
@enduml