@startuml
class utils.ImageUtil {
- {static} String BASE64_PREFIX
+ String convertTo64Base(ImageView)
+ void loadImage(String,ImageView)
}


class utils.SharedPreferencesUtil {
- {static} String PREF_NAME
- {static} String KEY_USER
- {static} String KEY_DARK_MODE
- {static} String KEY_FALL_DETECTION_ENABLED
- SharedPreferences sharedPreferences
- Gson gson
+ void saveString(String,String)
+ String getString(String,String)
+ void saveInt(String,int)
+ int getInt(String,int)
+ void saveBoolean(String,boolean)
+ boolean getBoolean(String,boolean)
+ void clear()
+ void remove(String)
+ boolean contains(String)
+ void saveObject(String,T)
+ T getObject(String,Class<T>)
+ void saveUser(User)
+ User getUser()
+ void signOutUser()
+ boolean isUserNotLoggedIn()
+ boolean isDarkMode()
+ void setDarkMode(boolean)
+ boolean isFallDetectionEnabled()
+ void setFallDetectionEnabled(boolean)
}


class utils.CalendarUtil {
+ {static} String DEFAULT_DATE_FORMAT
+ {static} String DATABASE_DATE_FORMAT
+ {static} String DATABASE_TIMESTAMP_FORMAT
+ void openDatePicker(Context,String,OnDateSelectedListener,boolean,boolean,String)
+ long parseDateFromDatabase(String)
+ long parseTimestampFromDatabase(String)
+ String getCurrentDate()
+ String getCurrentTimestamp()
+ String formatDate(long)
+ String formatDate(long,String)
- long parse(String,String)
}


interface utils.CalendarUtil$OnDateSelectedListener {
~ void onDateSelected(long,String,String)
}

class utils.Validator {
- {static} int MIN_AGE
+ boolean isNameNotValid(String)
+ boolean isEmailNotValid(String)
+ boolean isPhoneNotValid(String)
+ boolean isPasswordNotValid(String)
+ boolean isAgeNotValid(String)
}




utils.CalendarUtil +.. utils.CalendarUtil$OnDateSelectedListener
@enduml